<?php

/**
 * This file is autogenerated using the goadmin.py program
 * Note: check the class in groupoffice/go/base/Module.php
 * for a complete list of overridable functions
 */

/**
 * 
 * The {{name}} module maintenance class
 * 
 */
class GO_{{name | capitalize}}_{{name | capitalize}}Module extends GO_Base_Module{
	
	public function autoInstall() {
		return true; # Set to false to prevent auto install on groupoffice installation
	}
	
	public function depends(){
		return array(); # add modules this module depends on
	}
	
	public function author() {
		return '{{username}}';
	}
	
	public function authorEmail() {
		return '{{email}}';
	}
	
	public function copyright() {
		return '{{copyright}}';
	}
	
	public function adminModule(){
		return false; # change this to true if you want the module to appear
		              # in the admin section of the start menu
	}

	
	/**
	 * 
	 * When a user is created, updated or logs in this function will be called.
	 * The function can check if the default calendar, addressbook, notebook etc.
	 * is created for this user.
	 * 
	 */
	public static function firstRun(){
		parent::firstRun();
		
		return array('exportVariables'=>array(
			'GO'=>array(
				"{{name}}"=>array(
				
				)
			)
		));
	}

	/**
	 * Called when the module is installed. Use this function to create any 
	 * default fixtures or properties
	 */	
	public function install() {
		parent::install();
	}
}
